devmind:
  name: Dev-Mind
  city: Saint Etienne
  twitter: DevMind_FR


spring:
  datasource:
    driver-class-name: ${DATABASE_DRIVER:com.mysql.jdbc.Driver}
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_SCHEMA:devmind}
    username: ${DATABASE_USERNAME:devmind}
    password: ${DATABASE_PASSWORD:devmind}


---
spring:
  profiles: default
cesar:
  devmind.city=Saint Etienne
---
spring:
  profiles: cloud
  server:
    port: 80